name: Pull Request

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog-comment:
    name: changelog preview
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/on-pr-changelog.yml
    with:
      ref: ${{ github.ref }}
      base-ref: origin/${{ github.base_ref }}
      pr-number: ${{ github.event.pull_request.number }}
      changelog-required: ${{ !contains(github.event.pull_request.labels.*.name, 'impact/no-changelog-required') }}
    secrets: inherit

  info:
    name: info
    uses: ./.github/workflows/ci-info.yml
    permissions:
      contents: read
    with:
      ref: ${{ github.ref }}
      is-snapshot: true
    secrets: inherit

  ci:
    name: CI
    needs: [info]
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      id-token: write
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.info.outputs.version }}
      lint: true
      build-all-targets: ${{ contains(github.event.pull_request.labels.*.name, 'ci/test') }}
      test-version-sets: >- # No newlines or trailing newline.
        ${{
          contains(github.event.pull_request.labels.*.name, 'ci/test')
          && 'minimum current'
          || 'current'
        }}
      integration-test-platforms: ubuntu-latest
      smoke-test-platforms: >- # No newlines or trailing newline.
        ${{
          contains(github.event.pull_request.labels.*.name, 'ci/test')
          && 'macos-11 windows-latest'
          || ''
        }}
      enable-coverage: true
    secrets: inherit

  prepare-release:
    name: prepare
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/test') }}
    needs: [info, ci]
    uses: ./.github/workflows/ci-prepare-release.yml
    permissions:
      contents: write
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.info.outputs.version }}
      release-notes: ${{ needs.info.outputs.release-notes }}
      project: ${{ github.repository }}
      draft: true
      prerelease: true
    secrets: inherit

  # release:
  #   name: release
  #   if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/test') }}
  #   needs: [info, matrix, prepare-release]
  #   uses: ./.github/workflows/release.yml
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   with:
  #     ref: ${{ github.ref }}
  #     version: ${{ needs.info.outputs.version }}
  #     release-notes: ${{ needs.info.outputs.release-notes }}
  #     version-set: ${{ needs.matrix.outputs.version-set }}
  #     queue-merge: false
  #   secrets: inherit
